/**
 * 
 */
package com.yahoo.petermwenda83;

import java.util.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

import org.apache.log4j.Logger;

/**
 * @author pmnjeru
 *
 */
public class ThreadManager implements ServletContextListener {

	private Logger logger = Logger.getLogger(this.getClass());
	private ThreadPoolExecutor executor = null;

	/**
	 * 
	 */
	public ThreadManager() {
		// TODO Autogenerated constructor stub
	}

	@Override
	public void contextDestroyed(ServletContextEvent arg0) {
		try {
			System.out.println("Scheduler Shutting down successfully " + new Date());
			executor.shutdown();
		} catch (Exception ex) {
		}
	}

	@Override
	public void contextInitialized(ServletContextEvent arg0) {

		if ((executor == null) || (!executor.isTerminated())) {
			// executor = Executors.newSingleThreadScheduledExecutor();
			executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(2);
			logger.info("Starting duplicate checker");
			executor.execute(new DuplicateChecker()); 
			//executor.scheduleAtFixedRate(new ScheduledTask(), 0, 3, TimeUnit.SECONDS);
			logger.info("duplicate checker started");
			
		}

	}

}
