

###############################################
#
#
##############################################
#==========================================================
# Database Settings
# The platform is currently using Postgres 8 or higher
#==========================================================
DATABASE_HOST = localhost
DATABASE_USERNAME = school
DATABASE_PASSWORD = AllaManO1
DATABASE_NAME = schooldb
DATABASE_POOL_SIZE = 10

#=========
# P1,2 and 3 Exam Id
#=======
PAPER_1_2_3_ID = C3915245-00EE-4EF4-9898-ACE59683DD60 


#==========================================================
# Cache Management
# For more details, read about Ehcache
#==========================================================
MAX_BYTES_LOCAL_HEAP = 20971520
MAX_BYTES_LOCAL_DISK = 1048576000
CACHE_FILE = school-new

#==========================================================
# Account Management
#==========================================================
# Variables to do with the administrator session
ADMIN_USERNAME = admin
ADMIN_PASSWORD = admin
ENCRYPT_PASSWORD = Vuwachip2

REST_USERNAME = demo
REST_PASSWORD = 12345678

REST_ADMIN_USERNAME = comPlex 
REST_ADMIN_PASSWORD = reSt*@!Api




