
org.quartz.shcheduler.instanceName = QuartzScheduler
org.quartz.scheduler.skipUpdateCheck = true
#==============================================================
# Configuration for ThreadPool settings
# Configure ThreadPool
#==============================================================
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 3
org.quartz.threadPool.threadPriority = 5
#==============================================================
# Configuring Quartz to use JobStoreTx
#==============================================================
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
#==============================================================
# Configuring JDBCJobStore to use a DriverDelegate
#==============================================================
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#==============================================================
# Configuring JDBCJobStore with the Table Prefix
#==============================================================
org.quartz.jobStore.tablePrefix = QRTZ_
#==============================================================
# Configuring JDBCJobStore with the name of the DataSource to
# use
#==============================================================
org.quartz.jobStore.dataSource = fms 
#==============================================================
# Configuring JDBCJobStore with  DataSource to
# use
#==============================================================
org.quartz.dataSource.fms.driver = org.postgresql.Driver
org.quartz.dataSource.fms.URL = jdbc:postgresql://localhost:5432/quartz_db
org.quartz.dataSource.fms.user = quartz_user 
org.quartz.dataSource.fms.password = quartz_password
org.quartz.dataSource.fms.maxConnections = 10

